[toolchain]
package_manager = "yarn"

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_bridge = "FbNDA92F4xaU7C6maWPB8ceQGjEWedcmB2YyFN8QLj5f"
amm = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
bridge = "GDDMwNyyx8uB6zrqwBFHjLLG3TBYk2F8Az4aBqxXUj9q"

[programs.devnet]
amm = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
bridge = "GDDMwNyyx8uB6zrqwBFHjLLG3TBYk2F8Az4aBqxXUj9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/amm",
    "programs/bridge"
]